"""create catalog tables

Revision ID: 409e2093bb6c
Revises: 
Create Date: 2026-08-31 15:56:30.406755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409e2093bb6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('category_code', sa.String(length=255), nullable=True),
    sa.Column('category_l1', sa.String(length=100), nullable=True),
    sa.Column('category_leaf', sa.String(length=100), nullable=True),
    sa.Column('total_events', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('carts', sa.BigInteger(), nullable=False),
    sa.Column('purchases', sa.BigInteger(), nullable=False),
    sa.Column('unique_products', sa.BigInteger(), nullable=False),
    sa.Column('unique_users', sa.BigInteger(), nullable=False),
    sa.Column('view_to_purchase_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('ix_categories_category_code', 'categories', ['category_code'], unique=False)
    op.create_index('ix_categories_category_l1', 'categories', ['category_l1'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_code', sa.String(length=255), nullable=True),
    sa.Column('category_l1', sa.String(length=100), nullable=True),
    sa.Column('category_leaf', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('total_events', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('carts', sa.BigInteger(), nullable=False),
    sa.Column('removes', sa.BigInteger(), nullable=False),
    sa.Column('purchases', sa.BigInteger(), nullable=False),
    sa.Column('unique_users', sa.BigInteger(), nullable=False),
    sa.Column('unique_sessions', sa.BigInteger(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('view_to_purchase_rate', sa.Float(), nullable=False),
    sa.Column('view_to_cart_rate', sa.Float(), nullable=False),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index('ix_products_category_brand', 'products', ['category_id', 'brand'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_price', 'products', ['price'], unique=False)
    op.create_index('ix_products_purchases', 'products', ['purchases'], unique=False)
    op.create_index('ix_products_total_events', 'products', ['total_events'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_total_events', table_name='products')
    op.drop_index('ix_products_purchases', table_name='products')
    op.drop_index('ix_products_price', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('ix_products_category_brand', table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_categories_category_l1', table_name='categories')
    op.drop_index('ix_categories_category_code', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
