"""create interaction events table

Revision ID: 437db3ada2e3
Revises: 9ee89eb27a3a
Create Date: 2026-08-31 19:17:03.560123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '437db3ada2e3'
down_revision: Union[str, Sequence[str], None] = '9ee89eb27a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_category_id'), 'interaction_events', ['category_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_event_type'), 'interaction_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_interaction_events_product_id'), 'interaction_events', ['product_id'], unique=False)
    op.create_index('ix_interaction_events_product_occurred', 'interaction_events', ['product_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_interaction_events_session_id'), 'interaction_events', ['session_id'], unique=False)
    op.create_index('ix_interaction_events_session_occurred', 'interaction_events', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_interaction_events_type_occurred', 'interaction_events', ['event_type', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_events_type_occurred', table_name='interaction_events')
    op.drop_index('ix_interaction_events_session_occurred', table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_session_id'), table_name='interaction_events')
    op.drop_index('ix_interaction_events_product_occurred', table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_product_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_event_type'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_category_id'), table_name='interaction_events')
    op.drop_table('interaction_events')
    # ### end Alembic commands ###
